name: more_on_widgets
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/man.jpeg
    - lib/assets/images/woman.png
    - lib/assets/images/man_2.jpeg
    - lib/assets/images/woman1.png
    - lib/assets/images/image_3.png
    - lib/assets/images/image_31.png
    - lib/assets/images/image_4.png
    - lib/assets/images/image_41.png
    - lib/assets/images/image_last.jpeg
    
    